name: IronFactory
version: 1.0.0
main: com.factory.generators.IronFactory
api-version: '1.20'
author: User
description: Generator Factory Plugin

softdepend:
  - PlaceholderAPI
  - DecentHolograms

commands:
  factory:
    description: Main factory command
    usage: /<command> <args>
    aliases: [f, gen, generator]
    permission: factory.use

permissions:
  factory.use:
    description: Use factory commands
    default: true
  factory.admin:
    description: Admin commands
    default: op
  factory.give:
    description: Give generators
    default: op
  factory.reload:
    description: Reload config
    default: op
  factory.bypass:
    description: Bypass limits
    default: op
